name = "image-uploader"
compatibility_date = "2024-07-01"

# R2存储桶绑定配置
[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "your-bucket-name"
preview_bucket_name = "your-preview-bucket-name"

# 环境变量（在Cloudflare Workers中使用时）
[vars]
CUSTOM_DOMAIN = "static.k1r.in"
MAX_FILE_SIZE = 16777216  # 16MB in bytes

# 开发环境配置
[env.development]
vars = { ENVIRONMENT = "development" }

# 生产环境配置  
[env.production]
vars = { ENVIRONMENT = "production" }
